# Generated by Django 5.1.5 on 2025-01-27 19:06

import django.db.models.deletion
import products.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="image_name",
            field=models.ImageField(upload_to=products.utils.FileUpload.upload_to),
        ),
        migrations.AlterField(
            model_name="product",
            name="image_name",
            field=models.ImageField(upload_to=products.utils.FileUpload.upload_to),
        ),
        migrations.AlterField(
            model_name="productgallery",
            name="image_name",
            field=models.ImageField(upload_to=products.utils.FileUpload.upload_to),
        ),
        migrations.AlterField(
            model_name="productgroup",
            name="image_name",
            field=models.ImageField(upload_to=products.utils.FileUpload.upload_to),
        ),
        migrations.CreateModel(
            name="FeatureValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value_title", models.CharField(max_length=100)),
                (
                    "feature",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_value",
                        to="products.feature",
                    ),
                ),
            ],
        ),
    ]
