# Generated by Django 5.1.5 on 2025-01-28 07:39

import django.db.models.deletion
import products.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_alter_brand_image_name_alter_featurevalue_feature_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="image_name",
            field=models.ImageField(upload_to=products.utils.FileUpload.upload_to),
        ),
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_of_brand",
                to="products.brand",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image_name",
            field=models.ImageField(upload_to=products.utils.FileUpload.upload_to),
        ),
        migrations.AlterField(
            model_name="productgallery",
            name="image_name",
            field=models.ImageField(upload_to=products.utils.FileUpload.upload_to),
        ),
        migrations.AlterField(
            model_name="productgroup",
            name="image_name",
            field=models.ImageField(upload_to=products.utils.FileUpload.upload_to),
        ),
    ]
