# Generated by Django 5.1.5 on 2025-02-02 19:25

import products.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_alter_brand_image_name_alter_product_image_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="image_name",
            field=models.ImageField(upload_to=products.utils.FileUpload.upload_to),
        ),
        migrations.AlterField(
            model_name="product",
            name="image_name",
            field=models.ImageField(upload_to=products.utils.FileUpload.upload_to),
        ),
        migrations.AlterField(
            model_name="productgallery",
            name="image_name",
            field=models.ImageField(upload_to=products.utils.FileUpload.upload_to),
        ),
        migrations.AlterField(
            model_name="productgroup",
            name="image_name",
            field=models.ImageField(upload_to=products.utils.FileUpload.upload_to),
        ),
    ]
